development:
  adapter: mysql2
  database: reservester_development
  username: root
  password: 

test:
  adapter: mysql2
  database: reservester_test
  username: root
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: reservester
  pool: 5
  username: reservester
  password:

